# SQLALCHEMY_DATABASE_URI = "sqlite:///database.db"
# SQLALCHEMY_TRACK_MODIFICATIONS = False



# CLOUDINARY_CLOUD_NAME = 'dfdqp6bdl'
# CLOUDINARY_API_KEY = '322119454398727'
# CLOUDINARY_API_SECRET = 'yRGdFJRYQ9iaMi3Vm90enTrN5NI'