SQLALCHEMY_DATABASE_URI = "sqlite:///database.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False



CLOUDINARY_CLOUD_NAME = 'dfdqp6bdl'
CLOUDINARY_API_KEY = '542242258845743'
CLOUDINARY_API_SECRET = 'Olt7dxY6xlA6TGLROVt55vJTTj8'