"""updated-migrations

Revision ID: fa7f0a2f5f0e
Revises: 4d5f8fc7cb50
Create Date: 2025-03-21 10:34:27.437629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7f0a2f5f0e'
down_revision = '4d5f8fc7cb50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
